// Package wireguard generates WireGuard keypairs and client configs.
//
// Note: This is a config-generation helper for the API. Establishing the
// actual tunnel happens on the user's device using the OS WireGuard client.
package wireguard

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"

	"golang.org/x/crypto/curve25519"
)

type PrivateKey [32]byte

func NewPrivateKey() (PrivateKey, error) {
	var k PrivateKey
	if _, err := rand.Read(k[:]); err != nil {
		return k, err
	}
	// Clamp per Curve25519 spec.
	k[0] &= 248
	k[31] &= 127
	k[31] |= 64
	return k, nil
}

func (k PrivateKey) String() string {
	return base64.StdEncoding.EncodeToString(k[:])
}

func (k PrivateKey) PublicKey() string {
	var pub [32]byte
	curve25519.ScalarBaseMult(&pub, (*[32]byte)(&k))
	return base64.StdEncoding.EncodeToString(pub[:])
}

// Config holds the values needed to render a wg-quick config file.
type Config struct {
	ClientPrivKey string
	ClientAddress string
	DNS           string
	PeerPubKey    string
	PeerEndpoint  string
	AllowedIPs    string
	PresharedKey  string
}

func Render(c Config) string {
	allowed := c.AllowedIPs
	if allowed == "" {
		allowed = "0.0.0.0/0, ::/0"
	}
	dns := c.DNS
	if dns == "" {
		dns = "10.66.66.1"
	}
	out := fmt.Sprintf(`[Interface]
# Generated by Monkey VPN — keep this file safer than your last banana.
PrivateKey = %s
Address = %s
DNS = %s

[Peer]
PublicKey = %s
AllowedIPs = %s
Endpoint = %s
PersistentKeepalive = 25
`, c.ClientPrivKey, c.ClientAddress, dns, c.PeerPubKey, allowed, c.PeerEndpoint)
	if c.PresharedKey != "" {
		out += "PresharedKey = " + c.PresharedKey + "\n"
	}
	return out
}
